[package]

name            = "summed-area-table"
version         = "0.0.4"
authors         = ["Mohammed El Batya"]
description     = "Generic implementation of a summed area table"
documentation   = "https://github.com/forgemo/summed_area_table/blob/master/README.md"
homepage        = "https://github.com/forgemo/summed_area_table"
repository      = "https://github.com/forgemo/summed_area_table"
readme          = "README.md"
keywords        = ["summed", "integral", "image",  "haar", "face"]
license         = "Unlicense"


[dependencies]
nalgebra = "0.2.22"
num = "0.1.27"
